:enabled: true
:schedule:
  usage_bandwidth:
    cron: '0,20,40 * * * *'
    class: UsageBandwidth
  usage_storage:
    cron: '0 */4 * * *'
    class: UsageStorage

development:
  :logfile: ./log/sidekiq_development.log
  :verbose: true
  :concurrency: 1